import jsPDF from 'jspdf';
import html2canvas from 'html2canvas';

export const exportToPDF = async (elementId, filename = 'clinical-report.pdf') => {
    const element = document.getElementById(elementId);
    if (!element) return;

    // Temporarily hide the download button so it doesn't appear in the PDF
    const downloadBtn = element.querySelector('button');
    if (downloadBtn) downloadBtn.style.visibility = 'hidden';

    try {
        const canvas = await html2canvas(element, {
            scale: 2, // Higher scale for print quality
            useCORS: true,
            logging: false,
            backgroundColor: '#FFFBF5',
            windowWidth: element.scrollWidth,
            windowHeight: element.scrollHeight,
            onclone: (doc) => {
                // Ensure icons are rendered
                const clonedContent = doc.getElementById(elementId);
                clonedContent.style.padding = '40px';
                clonedContent.style.borderRadius = '0';
            }
        });

        const imgData = canvas.toDataURL('image/png', 1.0);
        const pdf = new jsPDF('p', 'mm', 'a4');

        const pdfWidth = pdf.internal.pageSize.getWidth();
        const pdfHeight = pdf.internal.pageSize.getHeight();

        const imgProps = pdf.getImageProperties(imgData);
        const ratio = Math.min(pdfWidth / imgProps.width, pdfHeight / imgProps.height);
        const imgWidth = imgProps.width * ratio;
        const imgHeight = imgProps.height * ratio;

        // Center horizontally
        const xOffset = (pdfWidth - imgWidth) / 2;

        pdf.addImage(imgData, 'PNG', xOffset, 10, imgWidth, imgHeight);

        // Footer
        pdf.setFontSize(8);
        pdf.setTextColor(150);
        pdf.text('Generated by Py-Chiatrist AI - Clinical Research Platform', 10, pdfHeight - 10);

        pdf.save(filename);
    } catch (err) {
        console.error("PDF Export Error:", err);
    } finally {
        if (downloadBtn) downloadBtn.style.visibility = 'visible';
    }
};
